version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - FAST_API_APP=run.py
      - FAST_API__ENV=development
